steps:
  # Step 1: Start pgvector container on the cloudbuild network
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '-d'
      - '--name=postgres'
      - '--network=cloudbuild'
      - '-e'
      - 'POSTGRES_USER=apexflow'
      - '-e'
      - 'POSTGRES_PASSWORD=apexflow'
      - '-e'
      - 'POSTGRES_DB=apexflow'
      - 'pgvector/pgvector:pg15'
    id: 'start-db'

  # Step 2: Wait for PostgreSQL to be ready
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet psycopg2-binary
        for i in $(seq 1 30); do
          python -c "
        import psycopg2
        try:
            conn = psycopg2.connect(host='postgres', user='apexflow', password='apexflow', dbname='apexflow')
            conn.close()
            exit(0)
        except:
            exit(1)
        " && break || sleep 2
        done
    id: 'wait-for-db'
    waitFor: ['start-db']

  # Step 3: Lint with ruff
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet ruff
        ruff check .
    id: 'lint'
    waitFor: ['-']

  # Step 4: Type check with mypy
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet -e ".[dev]"
        pip install --quiet asyncpg-stubs
        mypy core/
    id: 'typecheck'
    waitFor: ['-']

  # Step 5: Run Alembic migrations
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet -e ".[dev]"
        pip install --quiet psycopg2-binary
        export DB_HOST=postgres
        alembic upgrade head
    id: 'migrate'
    waitFor: ['wait-for-db']

  # Step 6: Run tests
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet -e ".[dev]"
        export DB_HOST=postgres
        pytest tests/ -v
    id: 'test'
    waitFor: ['migrate']

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
