steps:
  # Step 1: Start pgvector container on the cloudbuild network
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '-d'
      - '--name=postgres'
      - '--network=cloudbuild'
      - '-e'
      - 'POSTGRES_USER=apexflow'
      - '-e'
      - 'POSTGRES_PASSWORD=apexflow'
      - '-e'
      - 'POSTGRES_DB=apexflow'
      - 'pgvector/pgvector:pg15'
    id: 'start-db'

  # Step 2: Wait for PostgreSQL to be ready
  - name: 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        uv pip install --system psycopg2-binary
        for i in $(seq 1 30); do
          python -c "
        import psycopg2
        try:
            conn = psycopg2.connect(host='postgres', user='apexflow', password='apexflow', dbname='apexflow')
            conn.close()
            exit(0)
        except:
            exit(1)
        " && break || sleep 2
        done
    id: 'wait-for-db'
    waitFor: ['start-db']

  # Step 3: Lint with ruff (uvx runs ruff without installing into the project)
  - name: 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        uvx ruff check .
    id: 'lint'
    waitFor: ['-']

  # Step 4: Type check with mypy
  - name: 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        uv sync --extra dev
        uv run mypy core/
    id: 'typecheck'
    waitFor: ['-']

  # Step 5: Run Alembic migrations
  - name: 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        uv sync --extra dev
        export DB_HOST=postgres
        uv run alembic upgrade head
    id: 'migrate'
    waitFor: ['wait-for-db']

  # Step 6: Run tests
  - name: 'ghcr.io/astral-sh/uv:python3.12-bookworm-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        uv sync --extra dev
        export DB_HOST=postgres
        uv run pytest tests/ -v
    id: 'test'
    waitFor: ['migrate']

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
